.TH tiledb_version 1 "11 October 2015" "Version 0.1" "TileDB programs"
 
.SH NAME
tiledb_version - returns the TileDB version

.SH SYNOPSIS
.B tiledb_version

.SH DESCRIPTION
.B tiledb_version
simply returns the current TileDB verion.

.SH OPTIONS
This program takes no options.

.SH EXAMPLE
Simply type \fBtiledb_version\fR.

.SH EXIT STATUS
.TP 
\fB0\fR for success and \fB-1\fR for error.

.SH AUTHOR
Stavros Papadopoulos <http://people.csail.mit.edu/stavrosp>, Copyright (c) 2015
