[package]
name = "tiledb-proptest-array-schema"
edition = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
cxx = { workspace = true }
itertools = { workspace = true }
proptest = { workspace = true }
tiledb-api = { workspace = true }
tiledb-common = { workspace = true }
tiledb-pod = { workspace = true }
tiledb-oxidize = { workspace = true }
tiledb-test-support = { workspace = true }
