# Don't build any extra formats
formats: []

# Use RTD config version 2
# https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2

sphinx:
  configuration: doc/source/conf.py

python:
  version: 3.7
  install:
    # this order is important: we need cmake to build doxygen XML for breathe
    - requirements: doc/source/requirements.txt
