# Cloned from https://github.com/TileDB-Inc/tiledb-quarto-template
project:
  type: website
  output-dir: docs

format:
  html:
    toc: true
    theme: 
      light: [flatly, "quarto-materials/tiledb.scss"]
    mainfont: Helvetica
    fontsize: 1rem
    linkcolor: "#4d9fff"
    code-copy: true
    code-overflow: wrap
    css: "quarto-materials/tiledb.css"

website:
  favicon: "images/favicon.ico"
  repo-url: https://github.com/TileDB-Inc/TileDB
  page-navigation: true
  navbar:
    background: light
    logo: "quarto-materials/tiledb-logo.png"
    collapse-below: lg
    left:
      - text: "Home page"
        href: "https://tiledb.com"
      - text: "Contact us"
        href: "https://tiledb.com/contact"
      - text: "Repo"
        href: "https://github.com/TileDB-Inc/TileDB"

  sidebar:
    - id: placeholder
      title: ""
      style: "floating"
      collapse-level: 2
      align: left

      contents:
        - href: 'index.md'

        - section: 'Format Specification'
          href: "format_spec/FORMAT_SPEC.md"
          contents:
            - section: 'Array'
              contents:
                - href: "format_spec/array_file_hierarchy.md"
                - href: "format_spec/array_schema.md"
                - href: "format_spec/fragment.md"
                - href: "format_spec/array_metadata.md"
                - href: "format_spec/tile.md"
                - href: "format_spec/generic_tile.md"
            - section: 'Group'
              contents:
                - href: "format_spec/group_file_hierarchy.md"
            - section: 'Other'
              contents:
                - href: "format_spec/consolidated_fragment_metadata_file.md"
                - href: "format_spec/filter_pipeline.md"
                - href: "format_spec/vacuum_file.md"

        - section: 'Developer Docs'
          contents:
            - "doc/dev/style/index.md"
