name: msys2

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        include: [
          { msystem: MINGW64, toolchain: x86_64 },
          { msystem: MINGW32, toolchain: i686 },
          { msystem: ucrt64, toolchain: "ucrt-x86_64" }
        ]
      fail-fast: false
    env:
      TILEDB_HOME: ${{ github.workspace }}
      MINGW_INSTALLS: ${{ matrix.msystem }}
      MINGW_ARCH: ${{ matrix.msystem }}
      MINGW_TOOLCHAIN: ${{ matrix.toolchain }}
      PACMAN_REPOSITORY: ${{ matrix.msystem }}
    steps:
      - name: Prepare git
        run: git config --global core.autocrlf false
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          install: mingw-w64-${{ matrix.toolchain }}-toolchain make patch
          update: true
      - name: Building TileDB
        run: cd .github/workflows/mingw-w64-tiledb && makepkg-mingw --noconfirm --syncdeps
        env:
          PKGEXT: ".pkg.tar.xz"
        shell: msys2 {0}
