[workspace]
resolver = "2"
members = [
    "crates/enumeration",
    "crates/filter_pipeline"
]

[workspace.package]
edition = "2024"
rust-version = "1.85"
version = "0.1.0"

[workspace.dependencies]
anyhow = "1"
cxx = "1"
cxx-build = "1"
proptest = "1"
