name: Build-Dockerfile

on:
  pull_request:
    paths-ignore:
      - '_quarto.yml'
      - 'quarto-materials/*'
      - '**/.md'
      - 'doc/source/conf.py'
      - 'tiledb/sm/c_api/tiledb_version.h'

jobs:
  build-dockerfile:
    runs-on: ubuntu-20.04

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Build the Dockerfile
        run: docker build -f examples/Dockerfile/Dockerfile -t tiledb:dev .
