name: tiledb-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.5.0
  - cmake
  - breathe==4.7.3
  - zlib==1.2.11
  - bzip2>=1.0.0
  - zstd==1.3.3
  - lz4-c==1.8.0
  - pip:
    - sphinxcontrib-contentui
