[package]
name = "filter_pipeline"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["staticlib"]

[dependencies]
anyhow.workspace = true
cxx.workspace = true
proptest.workspace = true

[build-dependencies]
cxx-build.workspace = true
