[package]
name = "tiledb-unit-arithmetic"
edition = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[dependencies]
tiledb-arithmetic = { workspace = true }

[lib]
name = "oxidize_unit_arithmetic"
crate-type = ["staticlib"]
