[workspace]
resolver = "2"
members = [
  "arithmetic",
  "array_schema",
  "expr"
]

[workspace.package]
edition = "2024"
rust-version = "1.85"
version = "0.1.0"

[workspace.dependencies]
anyhow = "1"
array_schema = { path = "array_schema" }
cxx = "1"
cxx-build = "1"
datafusion = { version = "47", features = [] }
num-traits = "0.2"
