[workspace]
resolver = "2"
members = ["arithmetic", "bundle_rs", "datatype", "expr", "oxidize"]

[workspace.package]
edition = "2024"
rust-version = "1.85"
version = "0.1.0"

[workspace.dependencies]
arithmetic = { path = "arithmetic" }
datatype = { path = "datatype" }
expr = { path = "expr" }
oxidize = { path = "oxidize" }

anyhow = "1"
cxx = "1"
cxx-build = "1"
datafusion = { version = "47", features = [] }
itertools = { version = "0.14" }
num-traits = "0.2"
thiserror = { version = "2" }
