[workspace]
resolver = "2"
members = [
  "arithmetic",
  "expr",
  "oxidize",
]

[workspace.package]
edition = "2024"
rust-version = "1.85"
version = "0.1.0"

[workspace.dependencies]
anyhow = "1"
cxx = "1"
cxx-build = "1"
datafusion = { version = "47", features = [] }
itertools = { version = "0.14" }
num-traits = "0.2"
oxidize = { path = "oxidize" }
thiserror = { version = "2" }
