name: Append Release CMake

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Ref to be used as release'
        default: 'latest'
        required: true
        type: string
  workflow_call:
    inputs:
      ref:
        description: 'Ref to be used as release'
        default: 'latest'
        required: true
        type: string

jobs:
  generate_cmake_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout TileDB
        uses: actions/checkout@v3

      - name: Make release and output directories
        run: |
          mkdir release output

      - name: Github release data
        id: release_data
        uses: KevinRohn/github-full-release-data@v2.0.4
        with:
          # repository: 'TileDB-Inc/TileDB'
          version: ${{ inputs.ref }}
          asset-file: '*.zip,*.tar.gz'
          asset-output: './release/'

      - name: Render template
        run: |
          PATTERN="tiledb-([^-]+)-([^-]+)(-noavx2)?.(tar.gz|zip)$"
          RELLIST="output/releases.csv"
          MODULE="output/DownloadPrebuiltTileDB.cmake"
          cp cmake/inputs/DownloadPrebuiltTileDB.cmake $MODULE
          echo "os,arch,url,sha,noavx2" > $RELLIST
          
          for FILE in $(ls release)
          do
                  if [[ $FILE =~ $PATTERN ]]
                  then
                          OS=${BASH_REMATCH[1]^^}
                          ARCH=${BASH_REMATCH[2]^^}
                          NOAVX2=${BASH_REMATCH[3]//-/}

                          URL="${{ steps.release_data.outputs.assets_url }}/$FILE"
                          HASH=$(cat release/$FILE.sha256)
          
                          echo "${OS},${ARCH},${URL},${HASH},${NOAVX2^^}" >> $RELLIST
                  fi
          done
          
          SOURCE_FILE_NAME=$(ls release/tiledb-source-*.zip)
          URL_TILEDB_SOURCE=${{ steps.release_data.outputs.assets_url }}/$SOURCE_FILE_NAME
          HASH_TILEDB_SOURCE=$(cat release/$SOURCE_FILE_NAME.sha256)
          
          echo "source,source,${URL_TILEDB_SOURCE},${HASH_TILEDB_SOURCE},source" >> $RELLIST
          
          HASH=$(sha256sum $RELLIST | cut -d " " -f 1)
          echo $HASH > $RELLIST.sha256
          
          cat $RELLIST

      - name: Upload template to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: output/*
          tag: ${{ steps.release_data.outputs.tag_name }}
          overwrite: true
          file_glob: true