name: Append Release CMake

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Ref to be used as release'
        default: 'latest'
        required: true
        type: string
  workflow_call:
    inputs:
      ref:
        description: 'Ref to be used as release'
        default: 'latest'
        required: true
        type: string

jobs:
  generate_cmake_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout TileDB
        uses: actions/checkout@v3

      - name: Make release directory
        run: |
          mkdir release

      - name: Github release data
        id: release_data
        uses: KevinRohn/github-full-release-data@v2.0.4
        with:
          # repository: 'TileDB-Inc/TileDB'
          version: ${{ inputs.ref }}
          asset-file: '*.zip,*.tar.gz'
          asset-output: './release/'

      - name: Render template
        run: |
          PATTERN="tiledb-([^-]+)-([^-]+)(-noavx2)?.*"
          TEMPLATE=.github/misc/FindTileDB_EP.cmake

          for FILE in $(ls release)
          do
                  if [[ $FILE =~ $PATTERN ]]
                  then
                          OS=${BASH_REMATCH[1]^^}
                          ARCH=${BASH_REMATCH[2]^^}
                          NOAVX2=${BASH_REMATCH[3]//-/_}

                          REL=TILEDB_${OS}_${ARCH}${NOAVX2^^}
                          URL="https://github.com/TileDB-Inc/TileDB/releases/download/${{ inputs.ref }}/$FILE"
                          SHA=$(sha1sum release/$FILE | cut -d " " -f 1)

                          echo $REL
                          echo $URL
                          echo $SHA
          
                          cat $TEMPLATE | sed "s|{{URL_${REL}}}|$URL|g" > $TEMPLATE
                          cat $TEMPLATE
          
                          cat $TEMPLATE | sed "s|{{SHA_${REL}}}|$SHA|g" > $TEMPLATE
                          cat $TEMPLATE
                  fi
          done
          SHA=$(sha1sum $TEMPLATE | cut -d " " -f 1)
          echo $SHA > $TEMPLATE.sha
          ls .github/misc
          cat $TEMPLATE
          cat $TEMPLATE.sha

      - name: Upload template to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: .github/misc/FindTileDB_EP*
          tag: ${{ inputs.ref }}
          overwrite: true
          file_glob: true