name: Backport
on:
  issue_comment:
    types: [created]
  schedule:
    # once a day at 13:00 UTC to cleanup old runs
    - cron: '0 13 * * *'

permissions:
  contents: write
  issues: write
  pull-requests: write
  actions: write

jobs:
  backport:
    uses: dotnet/arcade/.github/workflows/backport-base.yml@66269f6a88f6062f2cccf6eb84660a8a6f5cc5ec
    with:
      pr_title_template: '[Backport %target_branch%] %source_pr_title% (#%source_pr_number%)'
      pr_description_template: |
        Backport of #%source_pr_number% to %target_branch%

        ---
        TYPE: NO_HISTORY | FEATURE | BUG | IMPROVEMENT | DEPRECATION | C_API | CPP_API | BREAKING_BEHAVIOR | BREAKING_API | FORMAT
        DESC: <short description>
      repository_owners: TileDB-Inc
