name: Backport
on:
  pull_request:
    types:
      - closed
      - labeled
    paths-ignore:
      - '_quarto.yml'
      - 'quarto-materials/*'
      - '**/.md'

jobs:
  backport:
    runs-on: ubuntu-18.04
    name: Backport
    steps:
      - name: Backport
        uses: tibdex/backport@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
