name: Check PR body

on:
  pull_request:
    types: [opened, edited]
    paths-ignore:
      - '_quarto.yml'
      - 'quarto-materials/*'
      - '**/.md'
      - 'doc/source/conf.py'
      - 'tiledb/sm/c_api/tiledb_version.h'

jobs:
  check_pr_body:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Run PR body checker
        run: |
          cat <<'EOF' | scripts/parse_pr.py
          ${{ github.event.pull_request.body }}
          EOF
