name: Check PR body

on:
  pull_request:
    types: [opened, edited]

jobs:
  check_pr_body:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Run PR body checker
        run: |
          cat <<'EOF' | scripts/parse_pr.py
          ${{ github.event.pull_request.body }}
          EOF
