name: "Full CI"
on:
  push:
    branches:
      - dev
      - release-*
      - refs/tags/*
    paths-ignore:
      - '.github/workflows/quarto-render.yml'
      - '_quarto.yml'
      - 'quarto-materials/*'
      - '**/.md'
      - 'doc/source/conf.py'
      - 'tiledb/sm/c_api/tiledb_version.h'
  pull_request:
    branches:
      - '*'  # must quote since "*" is a YAML reserved character; we want a string
    paths-ignore:
      - '.github/workflows/quarto-render.yml'
      - '_quarto.yml'
      - 'quarto-materials/*'
      - '**/.md'
      - 'doc/source/conf.py'
      - 'tiledb/sm/c_api/tiledb_version.h'

# NOTE: the job names below must be unique
jobs:
  ci1:
    #uses: ./.github/workflows/build-ubuntu20.04-AZURE.yml
    uses: ./.github/workflows/build-ubuntu20.04.yml
    with:
      ci_backend: AZURE
      matrix_image: ubuntu-20.04
      bootstrap_args: '--enable-azure --enable-release-symbols'
  ci2:
    uses: ./.github/workflows/build-ubuntu20.04.yml
    with:
      ci_backend: GCS
      matrix_image: ubuntu-20.04
      bootstrap_args: '--enable-gcs --enable-release-symbols'
  ci3:
    uses: ./.github/workflows/build-ubuntu20.04.yml
    with:
      ci_option: SERIALIZATION
      matrix_image: ubuntu-20.04
      bootstrap_args: '--enable-serialization --enable-release-symbols'

  ci4:
    uses: ./.github/workflows/build-ubuntu20.04.yml
    with:
      ci_backend: HDFS
      matrix_image: ubuntu-20.04
      bootstrap_args: '--enable-hdfs'

  ci5:
    uses: ./.github/workflows/build-ubuntu20.04.yml
    with:
      ci_backend: S3
      matrix_image: macos-11
      bootstrap_args: '--enable=s3,serialization,tools --enable-release-symbols'
  ci6:
    uses: ./.github/workflows/build-ubuntu20.04.yml
    with:
      ci_backend: GCS
      matrix_image: macos-11
      bootstrap_args: '--enable-gcs --enable-release-symbols'

  ci7:
    uses: ./.github/workflows/build-ubuntu20.04.yml
    with:
      ci_backend: GCS
      matrix_image: ubuntu-22.04
      bootstrap_args: '--enable=experimental-features,serialization --enable-release-symbols'