name: "Full CI"
on:
  push:
    branches:
      - pd/*
      - dev
      - release-*
      - refs/tags/*

    ##############################################################################
    #                                                                            #
    #    These sections must be synchronized with 'paths' in full-ci-dummy.yml   #
    #                                                                            #
    ##############################################################################

  pull_request:
    branches:
      - '*'  # must quote since "*" is a YAML reserved character; we want a string
    paths-ignore:
      - '.github/workflows/quarto-render.yml'
      - '_quarto.yml'
      - 'quarto-materials/*'
      - '**/.md'
      - 'tiledb/doxygen/source/*'
      - 'tiledb/sm/c_api/tiledb_version.h'

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

## NOTE: the job ids below must be unique!
jobs:
  ci_msvc:
    uses: ./.github/workflows/build-windows.yml

  # dummy job for branch protection check
  full_ci_passed:
    needs: [
        ci_msvc
      ]
    runs-on: ubuntu-22.04
    steps:
      - name: ''
        run: echo "Complete"
