on:
  schedule:
    # runs every day at 2:50 UTC
    - cron: "50 02 * * *"
  workflow_dispatch:

jobs:
  ci4:
    uses: ./.github/workflows/ci-linux_mac.yml
    with:
      ci_backend: HDFS
      matrix_image: ubuntu-22.04
      matrix_compiler_cc: 'gcc-13'
      matrix_compiler_cxx: 'g++-13'
      timeout: 120
      bootstrap_args: '--enable-hdfs --enable-static-tiledb --disable-werror'
