name: Prepare new release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version to be released'
        required: true
      branch:
        description: 'Release branch'
        required: true

jobs:
  prepare_release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: pip install PyGithub

      - name: Update version and history
        run: python ./scripts/prepare_release.py ${{ github.event.inputs.version }} --token="${{ secrets.GITHUB_TOKEN }}"

      - name: Commit and push updates
        uses: test-room-7/action-update-file@v1
        with:
          branch: ${{ github.event.inputs.branch }}
          file-path: |
            HISTORY.md
            doc/source/conf.py
            tiledb/sm/c_api/tiledb_version.h
          commit-msg: "${{ github.event.inputs.version }} release notes, version update"
          github-token: ${{ secrets.GITHUB_TOKEN }}
